force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Party__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Party__c/fields/start_date__c.field-meta.xml
<CustomField>
    <fullName>start_date__c</fullName>
    <label>start date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventBatchTest.cls
@isTest
private class EventBatchTest {

    @isTest
    static void check() {
        List<Party__c> partyObjTest = new List<Party__c>();
        for (Integer i = 0; i < 2; i++) {
            Party__c  party = new Party__c();  
            party.Name = 'teste homi' +  i ;
            party.email__c = 'selton569@gmail.com';
            party.start_date__c = Date.today();
            partyObjTest.add(party);
        } 

        insert partyObjTest;

        Test.startTest();
        EventBatch bat = new EventBatch();
        Database.executeBatch(bat);
        Test.stopTest();
    }
}