force-app/main/default/objects/Date_Drop__c/Date_Drop__c.object-meta.xml
<CustomObject>
    <label>Date Drop</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Date Drop Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Date Drops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Date_Drop__c/fields/Date_Finish__c.field-meta.xml
<CustomField>
    <fullName>Date_Finish__c</fullName>
    <label>Date Finish</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Date_Drop__c/fields/Date_Start__c.field-meta.xml
<CustomField>
    <fullName>Date_Start__c</fullName>
    <label>Date Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Date_Drop__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Date Drops</relationshipLabel>
    <relationshipName>Date_Drops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Date_Drop__c/fields/Value_Drop__c.field-meta.xml
<CustomField>
    <fullName>Value_Drop__c</fullName>
    <label>Value Drop</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PP,</fullName>
            </value>
            <value>
                <fullName>P,</fullName>
            </value>
            <value>
                <fullName>M,</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>GG,</fullName>
            </value>
            <value>
                <fullName>GGG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StockTest.cls
@isTest
private class StockTest {

     @isTest
     static void testCreateStock() {
         List<Date_Drop__c> listDate = createListDrop();
         List<Stock__c> listStockItem = createListStockItem();
         Test.startTest();
         Boolean result =  Stock.createStock('a02Hs000017dZx2IAE', listDate, listStockItem);
         Test.stopTest();
         System.assertEquals(true, result);
     }

     private static List<Date_Drop__c> createListDrop (){
        List<Date_Drop__c> listDrop = new List<Date_Drop__c>();

         Date_Drop__c drop = new Date_Drop__c();
         drop.Date_Start__c = Date.valueOf('2024-02-27');
         drop.Date_Finish__c =Date.valueOf('2024-02-29');
         drop.Value_Drop__c = 2;

         Date_Drop__c dropr = new Date_Drop__c();
         dropr.Date_Start__c = Date.valueOf('2024-02-17');
         dropr.Date_Finish__c = Date.valueOf('2024-03-12');
         dropr.Value_Drop__c = 24;

         listDrop.add(drop);
         listDrop.add(dropr);

         return listDrop;
    }

    private static List<Stock__c> createListStockItem() {
         List<Stock__c> listItem = new List<Stock__c>();

         Stock__c itemr = new Stock__c();
         itemr.Name = 'as';
         itemr.Size__c = 'M';
         itemr.Quantity__c = 54;
    
         listItem.add(itemr);

         return listItem;
    }

}